import {dominantSettlementDate,ensureSettlementDateColumn} from '../_settlement-date.js';

const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8'}});
function normalizePhone(v=''){let d=String(v||'').replace(/\D/g,'');if(d.startsWith('962'))d='0'+d.slice(3);else if(d.length===9&&d.startsWith('7'))d='0'+d;return d}
async function auth(request,env){const h=request.headers.get('authorization')||'',token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)return null;return env.DB.prepare(`SELECT u.id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>datetime('now') AND u.is_active=1`).bind(token).first()}
export async function onRequestPost({request,env}){
 const me=await auth(request,env);if(!me)return json({error:'غير مصرح'},401);const b=await request.json().catch(()=>({})),storeId=Number(b.store_id||0),sourceName=String(b.source_name||''),rows=Array.isArray(b.rows)?b.rows.slice(0,3000):[];if(!storeId||!rows.length)return json({error:'لا توجد نتائج للاعتماد'},400);
 await ensureSettlementDateColumn(env);
 const accepted=[];let unmatched=0,duplicate=0,review=0;const used=new Set();
 for(const r of rows){const id=Number(r.order_id||r.order?.id||0),type=String(r.match_type||'');if(!id||!['matched','matched_partial'].includes(type)){if(type==='duplicate')duplicate++;else if(type.startsWith('review'))review++;else unmatched++;continue}if(used.has(id)){duplicate++;continue}
  const o=await env.DB.prepare(`SELECT o.*,CASE WHEN o.first_printed_at IS NULL THEN NULL WHEN strftime('%w',o.first_printed_at,'+3 hours')='4' THEN date(o.first_printed_at,'+3 hours','+2 days') ELSE date(o.first_printed_at,'+3 hours','+1 day') END delivery_date FROM orders o WHERE o.id=? AND o.store_id=? AND COALESCE(o.delivery_company_settled,0)=0`).bind(id,storeId).first();if(!o){unmatched++;continue}const phone=normalizePhone(r.phone),orderPhone=normalizePhone(o.phone),amount=Math.max(0,Number(r.amount||0)),original=Math.abs(Number(o.amount||0));
  if(phone!==orderPhone){review++;continue}if(amount>original+.001){review++;continue}if(type==='matched'&&Math.abs(amount-original)>.001){review++;continue}used.add(id);accepted.push({o,r,amount,type})
 }
 if(!accepted.length)return json({error:'لا توجد طلبات آمنة للاعتماد. راجع اختلاف الهاتف/القيمة أولاً.',review,unmatched,duplicate},400);
 const code='DC-'+Date.now();let delivered=0,refused=0,collected=0,fees=0,net=0;const prepared=[];
 for(const x of accepted){let status=String(x.r.status||'pending');if(x.type==='matched_partial'&&status==='delivered')status='partial';if(status==='delivered_adjusted')status='partial';const fee=Math.max(0,Number(x.r.delivery_fee||0))||Number(x.o.delivery_fee||2),isDel=['delivered','partial'].includes(status),isRef=['refused_fee_paid','refused_no_fee','canceled_before_arrival'].includes(status),hasNet=Boolean(x.r.has_net),importedNet=Number(x.r.net_amount||0),cash=hasNet?importedNet:(isDel?Math.max(0,x.amount-fee):(status==='refused_no_fee'?-fee:0));if(isDel)delivered++;else if(isRef)refused++;collected+=isDel?x.amount:0;fees+=(isDel||isRef)?fee:0;net+=cash;prepared.push({...x,status,fee,cash})}
 const statementDate=dominantSettlementDate(prepared.map(x=>({shipment_date:x.r.shipment_date||x.o.delivery_date})));
 const ins=await env.DB.prepare(`INSERT INTO delivery_company_settlements(settlement_code,store_id,source_name,matched_count,unmatched_count,duplicate_count,delivered_count,refused_count,pending_count,collected_amount,delivery_fees,net_due,created_by,statement_date) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(code,storeId,sourceName,prepared.length,unmatched+review,duplicate,delivered,refused,prepared.length-delivered-refused,collected,fees,net,me.id,statementDate||null).run(),sid=ins.meta.last_row_id;
 for(const x of prepared){await env.DB.prepare(`UPDATE orders SET delivery_status=?,delivered_amount=?,cash_collected=?,delivery_fee=?,settled_at=CASE WHEN ?='pending' THEN NULL ELSE datetime('now') END,delivery_company_settled=CASE WHEN ?='pending' THEN 0 ELSE 1 END,delivery_company_settlement_id=?,updated_at=datetime('now') WHERE id=?`).bind(x.status,x.amount,x.cash,x.fee,x.status,x.status,sid,x.o.id).run();await env.DB.prepare(`INSERT INTO delivery_company_settlement_orders(settlement_id,order_id,phone,imported_status,applied_status,imported_amount,note,match_type) VALUES(?,?,?,?,?,?,?,?)`).bind(sid,x.o.id,normalizePhone(x.r.phone),String(x.r.status||''),x.status,x.amount,String(x.r.note||''),x.type).run()}
 return json({settlement:{id:sid,settlement_code:code,statement_date:statementDate||null,matched_count:prepared.length,unmatched_count:unmatched+review,duplicate_count:duplicate,delivered_count:delivered,refused_count:refused,collected_amount:collected,delivery_fees:fees,net_due:net},review_count:review})
}
